spring:
  application:
    name: ms-order

  mongodb:
    uri: mongodb://root:password@localhost:27017/order-db?authSource=admin

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

  sqs:
    queues:
      order-queue: order-queue
      order-callback-queue: order-callback-queue

server:
  port: 8079
