spring:
  application:
    name: ms-order

  data:
    mongodb:
      uri: ${MONGO_DB_URI}

  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}

  sqs:
    queues:
      order-queue: ${SQS_ORDER_QUEUE}
      order-callback-queue: ${SQS_ORDER_CALLBACK_QUEUE}

server:
  port: 8079
