spring:
  application:
    name: ms-order

  data:
    mongodb:
      uri: mongodb://root:password@order-db:27017/order-db?authSource=admin

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localstack:4566

  sqs:
    queues:
      order-queue: order-queue
      order-callback-queue: order-callback-queue

  devtools:
    restart:
      exclude: "**/generated-sources/**,**/*MapperImpl.class"

server:
  port: 8079
