apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-order-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: dev
  AWS_REGION: us-east-1
  SQS_ORDER_QUEUE: https://sqs.us-east-1.amazonaws.com/056075870573/order-queue
  SQS_ORDER_CALLBACK_QUEUE: https://sqs.us-east-1.amazonaws.com/056075870573/order-callback-queue

