name: CD - Production

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  CLUSTER_NAME: nextime-cluster

jobs:
  deploy-prod:
    name: Build, Terraform & Deploy (Prod)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-order
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e Push da imagem
        env:
          ECR_REPOSITORY: ms-order
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ECR_URI="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY"
          docker build -t $ECR_URI:$IMAGE_TAG .
          docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
          docker push $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve

      - name: Configure kubectl
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.CLUSTER_NAME }}

      - name: Atualizar Deployment com nova imagem
        run: |
          IMAGE_URI="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/ms-order:${{ github.sha }}"
          kubectl set image deployment/ms-order-deployment ms-order=$IMAGE_URI
          kubectl rollout status deployment/ms-order-deployment

      - name: Aplicar todos os manifests do Kubernetes
        working-directory: infra/k8s
        run: |
          kubectl apply -f .
